w3c/picture-in-picture

index.bs
index.html

@mounirlamouri As promised, here it is.
FYI, bikeshed is not happy:
```
LINK ERROR: No 'dfn' refs found for 'htmlvideoelement'.
<a data-link-type="dfn" data-lt="HTMLVideoElement"><code>HTMLVideoElement</code></a>
LINK ERROR: No 'dfn' refs found for 'remote playback specification'.
<a data-link-type="dfn" data-lt="Remote Playback specification">Remote Playback specification</a>
LINK ERROR: No 'dfn' refs found for 'feature policy specification'.
<a data-link-type="dfn" data-lt="Feature Policy specification">Feature Policy specification</a>
```

Add initial spec based on explainer

---

index.bs

As of now, there seems to be no implementer willing to support the ability to set pip Window positions and dimensions, so let's drop it. We'll see if it comes back later.
FIX: #https://github.com/WICG/picture-in-picture/issues/5

Remove PictureInPictureOptions

---

index.bs

Once https://github.com/tabatkins/bikeshed/pull/1177 is reviewed, merged, and live, this spec may have a proper "PiP" favicon.

Add favicon to spec

---

index.bs

This CL does 2 things:
- Use "fire an event" instead of deprecated "fire a simple event"
- Make video "enterpictureinpicture" and "leavepictureinpicture" events fired with bubbles set to true

Fire video events with bubbles set to true

---

index.bs

I'm reordering error steps so that web developer can take much easier some actions on this.
1. PiP is not enabled (you can't do anything)
2. Feature Policy prevents you to use PiP (update it if you can)
3. Video attribute prevents you to use PiP (remove it)

Reorder error steps in request PiP

---

explainer.md
index.bs

It turns out `Element` is required for `pictureInPictureElement` as it needs to return shadow root elements as well.
This CL updates spec and explainer.

s/HTMLVideoElement/Element for pictureInPictureElement

---

index.bs

This change allows Picture-in-Picture feature to be allowed by default to documents in child frames.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/63.html" title="Last updated on Feb 20, 2018, 8:01 AM GMT (ed5c087)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/63/1c75942...ed5c087.html" title="Last updated on Feb 20, 2018, 8:01 AM GMT (ed5c087)">Diff</a>

Update feature policy default allowlist to *

---

index.bs

This PR makes sure this spec is compliant with the implementation of [`webkitSupportsPresentationMode`](https://developer.apple.com/documentation/webkitjs/htmlvideoelement/1629816-webkitsupportspresentationmode) where it says Picture-in-Picture can't be triggered if `loadedmetadata` event has not fired, and if the files are audio-only.
I've picked `InvalidStateError` for the error returned by `requestPictureInPicture()`. Let me know what you think.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/64.html" title="Last updated on Apr 24, 2018, 7:54 AM GMT (3288a29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/64/c903374...3288a29.html" title="Last updated on Apr 24, 2018, 7:54 AM GMT (3288a29)">Diff</a>

Reject when metadata are not loaded or video has no video track

---

index.bs

As raised in https://chromium-review.googlesource.com/c/chromium/src/+/1025832/10/third_party/blink/renderer/modules/picture_in_picture/document_picture_in_picture.cc#48, this spec should set the task source used for entering and leaving Picture-in-Picture.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/65.html" title="Last updated on May 3, 2018, 12:18 PM GMT (ac84628)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/65/57c1d46...ac84628.html" title="Last updated on May 3, 2018, 12:18 PM GMT (ac84628)">Diff</a>

Specify task source

---

index.bs

Following Safari's implementation, video playback MUST not pause when exiting Picture-in-Picture from the API.
@mounirlamouri WDYT of this simple change?
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/73.html" title="Last updated on Jun 12, 2018, 5:19 AM GMT (fbd8519)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/73/2ed9c31...fbd8519.html" title="Last updated on Jun 12, 2018, 5:19 AM GMT (fbd8519)">Diff</a>

Do not pause playback when exiting Picture-in-Picture

---

index.bs

We should resolve requestPictureInPicture with existing Picture-in-Picture window when video is already pictureInPictureElement.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/75.html" title="Last updated on Jun 15, 2018, 7:25 AM GMT (37447bf)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/75/77628ce...37447bf.html" title="Last updated on Jun 15, 2018, 7:25 AM GMT (37447bf)">Diff</a>

Abort requestPictureInPicture steps if video is pictureInPictureElement

---

explainer.md
index.bs

Following https://github.com/WICG/media-capabilities/issues/91, we should mark `requestPictureInPicture` and `exitPictureInPicture` as `[NewObject]` as a new object is always returned.

IDL for requestPictureInPicture and exitPictureInPicture should specify that a new object is returned

---

index.bs

As noted by @lukebjerring in https://github.com/web-platform-tests/wpt/pull/11916, the interface `PictureInPictureWindow` should inherit from `EventTarget`.
TBR @mounirlamouri

PictureInPictureWindow inherits from EventTarget

---

index.bs

Google, Inc. is now Google LLC. Added editor ID for Francois Beaufort and Mounir Lamouri.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/78.html" title="Last updated on Aug 24, 2018, 6:47 AM GMT (2ae5999)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/78/4f62711...2ae5999.html" title="Last updated on Aug 24, 2018, 6:47 AM GMT (2ae5999)">Diff</a>

Updated editors metadata

---

index.bs

FIX #81
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/83.html" title="Last updated on Sep 17, 2018, 5:44 AM GMT (8ce62f4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/83/6dca358...8ce62f4.html" title="Last updated on Sep 17, 2018, 5:44 AM GMT (8ce62f4)">Diff</a>

Add note about styles

---

index.bs

This simply states that Picture-in-Picture window aspect ratio is based on the video size.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/87.html" title="Last updated on Sep 28, 2018, 7:11 AM GMT (73cc97b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/87/d11dde2...73cc97b.html" title="Last updated on Sep 28, 2018, 7:11 AM GMT (73cc97b)">Diff</a>

Add note for aspect ratio

---

explainer.md
index.bs

This adds a bullet point in API requirements regarding the size of the Picture-in-Picture window.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/88.html" title="Last updated on Sep 28, 2018, 7:42 AM GMT (2734bdb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/88/d11dde2...2734bdb.html" title="Last updated on Sep 28, 2018, 7:42 AM GMT (2734bdb)">Diff</a>

Add window size API requirements

---

index.bs

@yoavweiss suggested adding some use cases for why we need `disablePictureInPicture`.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/103.html" title="Last updated on Nov 26, 2018, 11:44 AM GMT (652607b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/103/ed25bd1...652607b.html" title="Last updated on Nov 26, 2018, 11:44 AM GMT (652607b)">Diff</a>

Add use cases for disablePictureInPicture

---

index.bs

@yoavweiss noted that spec doesn't tell much about the obvious visibility state of the Picture-in-Picture window. This PR fixes this.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/102.html" title="Last updated on Nov 26, 2018, 11:36 AM GMT (da07e5e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/102/ed25bd1...da07e5e.html" title="Last updated on Nov 26, 2018, 11:36 AM GMT (da07e5e)">Diff</a>

Be more explicit about PiP window visibility

---

index.bs

It wasn't clear to @yoavweiss that the exit pip algorithm was run on document unload. This PR addresses this.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/106.html" title="Last updated on Nov 26, 2018, 12:30 PM GMT (08960b9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/106/ed25bd1...08960b9.html" title="Last updated on Nov 26, 2018, 12:30 PM GMT (08960b9)">Diff</a>

Exit pip on document unload

---

explainer.md

According to https://chromium-review.googlesource.com/c/chromium/src/+/1353928, autoplay doesn't work on muted video that are not visible. This PR makes sure we document `play()` instead.

Remove autoplay

---

index.bs

Matching https://dom.spec.whatwg.org/#mixin-documentorshadowroot.
***
<a href="https://pr-preview.s3.amazonaws.com/foolip/picture-in-picture/pull/114.html" title="Last updated on Jan 21, 2019, 2:07 PM UTC (03da806)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/114/658c859...foolip:03da806.html" title="Last updated on Jan 21, 2019, 2:07 PM UTC (03da806)">Diff</a>

Treat DocumentOrShadowRoot as an interface mixin

---

index.bs

FIX #116
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/117.html" title="Last updated on Feb 6, 2019, 7:54 AM UTC (d4858cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/117/ab2cfb7...d4858cd.html" title="Last updated on Feb 6, 2019, 7:54 AM UTC (d4858cd)">Diff</a>

Do not require user gesture if pictureInPictureElement is set

---

index.bs

I'd like to add a `:picture-in-picture` CSS pseudo-class (like Fullscreen API [has](https://fullscreen.spec.whatwg.org/#:fullscreen-pseudo-class)) to help web developers to customize their video player when video enters and leave Picture-in-Picture.
I hope that a simple CSS pseudo-class would help.
What do you think @jernoble, @scottlow, and @mounirlamouri?
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/120.html" title="Last updated on Mar 11, 2019, 11:36 AM UTC (bd2c1c7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/120/ab2cfb7...bd2c1c7.html" title="Last updated on Mar 11, 2019, 11:36 AM UTC (bd2c1c7)">Diff</a>

Add `:picture-in-picture` CSS pseudo-class

---

.travis.yml
deploy.sh

This enables Travis CI on the v2 branch. To be picked up by travis this update needs to be on both the master and v2 branch.
I will add another PR to change the deploy.sh script on the v2 branch to save the generated html to out/v2/index.html (so the URL would be https://wicg.github.io/picture-in-picture/v2/). This is why there is also a change to deploy.sh on master to only clear html files.

Enable CI for v2 branch

---

index.bs

Following discussions at https://groups.google.com/a/chromium.org/d/msg/blink-dev/X-qPSmdSR_g/mRKxdlVICgAJ and https://github.com/w3c/webcomponents/issues/804, this PR removes retargeting for the `:picture-in-picture` CSS pseudo class that was added at https://github.com/WICG/picture-in-picture/pull/120

Remove retargeting for CSS pseudo class

---

v2_explainer.md

I wrote an explainer for the arbitrary content based on @mounirlamouri's proposal document. I was thinking we should keep all the arbitrary content bits on a separate `v2` branch so we can iterate on it easily and fix issues and then when are ready we can merge it into master.
@beaufortfrancois @mounirlamouri WDYT?

Add explainer for v2 (arbitrary content)

---

index.bs

This breaks up concepts into concepts and video specific concepts. If we need it we can have arbitrary content concepts too.
We should also define "non-interactive arbitrary content" but I will come back to that in a future PR. I also left "Request Picture-in-Picture" under video specific as that requires further thought.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/132.html" title="Last updated on May 2, 2019, 4:16 PM UTC (4ce7237)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/132/b87d29c...4ce7237.html" title="Last updated on May 2, 2019, 4:16 PM UTC (4ce7237)">Diff</a>

Break concepts up into video specific concepts and concepts

---

index.bs

This PR rewords how event steps are fired according to #146.
FYI @marcoscaceres 
FIX #146
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/147.html" title="Last updated on Jun 3, 2019, 8:23 AM UTC (babd759)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/147/f8dae9f...babd759.html" title="Last updated on Jun 3, 2019, 8:23 AM UTC (babd759)">Diff</a>

Fix event fired steps

---

CONTRIBUTING.md
LICENSE.md
README.md
index.bs
security-privacy-questionnaire.md
w3c.json

- Update spec boilerplate (copyright, SOTD) to note Media WG ownership
- Update self-references from `wicg.github.io` to `w3c.github.io`
- Update `w3c.json` info
- Update document license to that used by the Media WG
Note the PR depends on https://github.com/tabatkins/bikeshed/pull/1498
... and should only be merged once the repo has been transferred to the W3C organization (#150)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/picture-in-picture/pull/157.html" title="Last updated on Jul 24, 2019, 2:34 PM UTC (4f373b0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/157/75d9c66...tidoust:4f373b0.html" title="Last updated on Jul 24, 2019, 2:34 PM UTC (4f373b0)">Diff</a>

Update spec info to point to Media WG

---

index.bs

Minor editorial updates to fix a few broken links and correct references:
- Drop custom definitions that are no longer needed
- Replace "triggered by user activation" with new user activation model (see https://github.com/whatwg/html/issues/5129)
- Use back ticks for values instead of var shorthand
- Drop link to feature name in Feature Policy (term no longer exists)
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/picture-in-picture/pull/174.html" title="Last updated on Jan 14, 2020, 4:34 PM UTC (f4b4902)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/174/4db5e80...tidoust:f4b4902.html" title="Last updated on Jan 14, 2020, 4:34 PM UTC (f4b4902)">Diff</a>

Fix cross-spec links and references

---

implementation-status.md

- Updated implementation status for Android. Currently PiP API is not implemented at all on android: https://bugs.chromium.org/p/chromium/issues/detail?id=806249#c63
- Added note about disabling auto PiP behaviour on Android

Update Android's implementation status

---

index.bs

closes #156 
closes #144
The check is not that "attribute is present", but that it has been set to "true"... the IDL attribute is always present, and always initializes to false. 
```
x = document.createElement("video")
x.disablePictureInPicture; // false
```

fix: check HTMLVideoElement/disablePictureInPicture attribute

---

index.bs

@yoavweiss suggested adding one section for Secure Context that explains why API is not restricted to Secure Context.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/105.html" title="Last updated on Nov 26, 2018, 12:15 PM GMT (2456bcd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/105/ed25bd1...2456bcd.html" title="Last updated on Nov 26, 2018, 12:15 PM GMT (2456bcd)">Diff</a>

Add Secure Context

---

.github/workflows/pr-push.yml
README.md
index.bs

Also drop the link to the "build passing" icon on Travis CI since we're no longer using Travis CI. No new icon that could replace that for now.
Context for the renaming: https://www.w3.org/2021/04/13-mediawg-minutes.html#t03
@beaufortfrancois Default branch name obviously needs to be updated before that PR gets merged! Happy to take care of that.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/203.html" title="Last updated on May 4, 2021, 3:33 PM UTC (cdabbfc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/203/8703d25...cdabbfc.html" title="Last updated on May 4, 2021, 3:33 PM UTC (cdabbfc)">Diff</a>

Rename default branch to "main"

---

index.bs

If `document.pictureInPictureElement` is true, PinP is enable and can run `document.exitPictureInPicture()` .
***
<a href="https://pr-preview.s3.amazonaws.com/youkinjoh/picture-in-picture/pull/205.html" title="Last updated on Aug 26, 2021, 1:34 AM UTC (ce7b332)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/205/1e8297a...youkinjoh:ce7b332.html" title="Last updated on Aug 26, 2021, 1:34 AM UTC (ce7b332)">Diff</a>

turn condition

---

index.bs

Add the internal UA slot 'initiators of active Picture-in-Picture sessions'
This allows other specs, like Compute Pressure, to know if a document
currently has an active Picture-in-Picture session.
This is related to https://github.com/WICG/compute-pressure/issues/83
***
<a href="https://pr-preview.s3.amazonaws.com/kenchris/picture-in-picture/pull/210.html" title="Last updated on Mar 22, 2022, 8:28 AM UTC (4349ce6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/210/fb22039...kenchris:4349ce6.html" title="Last updated on Mar 22, 2022, 8:28 AM UTC (4349ce6)">Diff</a>

Add the UA slot 'initiators of active Picture-in-Picture sessions'

---

index.bs

See https://dom.spec.whatwg.org/#firing-events-example
***
<a href="https://pr-preview.s3.amazonaws.com/dontcallmedom/picture-in-picture/pull/212.html" title="Last updated on Jun 8, 2022, 3:38 PM UTC (11dfefc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/212/58be154...dontcallmedom:11dfefc.html" title="Last updated on Jun 8, 2022, 3:38 PM UTC (11dfefc)">Diff</a>

Align event firing with DOM suggested phrasing

---

implementation-status.md

Following https://groups.google.com/a/chromium.org/g/blink-dev/c/jXkQiIVpxr8, Picture-in-Picture support is about to be enabled on Chrome on Android.
FYI @liberato-at-chromium

Add Chrome for Android support

---

implementation-status.md
index.bs

This PR is about removing the `autoPictureInPicture` HTMLVideoElement attribute from the spec. The only browser that implemented it for experimental purposes was Chrome and it never shipped.
@steimelchrome PTAL
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/216.html" title="Last updated on Dec 6, 2022, 4:56 AM UTC (082ab8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/216/0d2dac0...082ab8f.html" title="Last updated on Dec 6, 2022, 4:56 AM UTC (082ab8f)">Diff</a>

Remove autoPictureInPicture HTMLVideoElement attribute

---

index.bs

See #184. This PR makes the behaviour of `disablePictureInPicture` optional (it's currently inconsistently specified as OPTIONAL but with SHOULD requirements).
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/224.html" title="Last updated on Mar 21, 2024, 5:45 PM UTC (a567ade)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/224/e2c0312...a567ade.html" title="Last updated on Mar 21, 2024, 5:45 PM UTC (a567ade)">Diff</a>

Make disablePictureInPicture optional

---

explainer.md
index.bs

In response to https://github.com/w3c/picture-in-picture/issues/182, this clarifies that the goal for this API doesn't include arbitrary HTML content, and is scoped to HTMLVideoElement.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/221.html" title="Last updated on May 2, 2024, 1:04 PM UTC (66ba36d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/221/e2c0312...66ba36d.html" title="Last updated on May 2, 2024, 1:04 PM UTC (66ba36d)">Diff</a>

Update the spec and explainer to clarify scope

---

index.bs

FIX https://github.com/w3c/picture-in-picture/issues/226
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/227.html" title="Last updated on Jun 10, 2024, 6:58 AM UTC (b8bcff0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/227/8e59095...b8bcff0.html" title="Last updated on Jun 10, 2024, 6:58 AM UTC (b8bcff0)">Diff</a>

Replace return with resolve
