explainer.md

As people may be more comfortable with JavaScript than IDL, here's an exhaustive example. Let me know if that makes sense @mounirlamouri.

Add example

---

explainer.md

It would be great if the API would consider both LTR and RTL worlds.

s/left/start in PictureInPictureOptions

---

explainer.md

@mounirlamouri Just a nit there.

Fixed presentation mode state

---

explainer.md

@mounirlamouri I believe it is better to show promise there as well.

Resolve promise when exiting PiP in example

---

index.bs
index.html

Clean link-defaults

---

index.bs
index.html

Hey @mounirlamouri,
Here's a PR that addresses your feedback raised at #15.
Let me know what you think.
Preview at https://api.csswg.org/bikeshed/?url=https://github.com/beaufortfrancois/picture-in-picture/raw/addressFeedback/index.bs
FIX: #15

Address misc comments from mounirlamouri@

---

.gitignore

Add index.html to .gitignore file

---

index.bs

Add Issue Tracking

---

explainer.md

R: @mounirlamouri 
FIX: https://github.com/WICG/picture-in-picture/issues/8

Removed "for a given video" in explainer.md

---

index.bs

R: @mounirlamouri 
FIX: https://github.com/WICG/picture-in-picture/issues/23

Emphasize the fact the window is always on top

---

index.bs

FIX https://github.com/WICG/picture-in-picture/issues/22

Detail the reasons why PIP can't be triggered

---

index.bs

This PR is about adding a hint to disable Picture In Picture for a specific video element as some may not want this for some videos.
WDYT?

Add a way to disable PiP

---

index.bs

Cleaned request and exit PiP algos

---

CONTRIBUTING.md
README.md
explainer.md
index.bs

Let's use "Picture-in-Picture" instead of "Picture in Picture".

s/Picture in Picture/Picture-in-Picture/g

---

index.bs

Removed hint for preferred window size

---

index.bs

Updated feature policy name

---

explainer.md

Update explainer example

---

index.bs

@mounirlamouri WDYT?
FIX: https://github.com/WICG/picture-in-picture/issues/2

Add PictureInPictureWindow proxy to handle PiP Window resize

---

index.bs

Fix small nits

---

index.bs

The "exit PiP" algorithm already includes steps that were mentioned before this CL.

Fix flow in disablePictureInPicture

---

index.bs

FIX https://github.com/WICG/picture-in-picture/issues/42

Explained why only HTMLVideoElement in security

---

index.bs

Exit PiP throws InvalidStateError if no pip video

---

index.bs

Use 2 spaces indentation for IDL

---

index.bs

Fix DocumentOrShadowRoot hash

---

explainer.md

Add "Video Restrictions" section to explainer

---

.pr-preview.json

[PR Preview](https://github.com/tobie/pr-preview) makes it super easy to preview pull requests of specs and vizualize the changes they bring about.
Since github.com/wicg org has blanket install of pr-preview, adding a config file is all we need to be setup.

Add config file for PR Preview

---

index.bs

What do you think of this CL?
FIX #54
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/59.html" title="Last updated on Feb 12, 2018, 12:36 PM GMT (432b457)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/59/f69a02a...432b457.html" title="Last updated on Feb 12, 2018, 12:36 PM GMT (432b457)">Diff</a>

Reset Picture-in-Picture window dimensions

---

index.bs

FIX https://github.com/WICG/picture-in-picture/issues/70
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/71.html" title="Last updated on May 23, 2018, 7:07 AM GMT (e126a17)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/71/ff65407...e126a17.html" title="Last updated on May 23, 2018, 7:07 AM GMT (e126a17)">Diff</a>

Define PictureInPictureWindow resize event

---

explainer.md

Hey @mounirlamouri,
Does this make sense to you as well?

Fixed canvas.captureStream example

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/foolip/picture-in-picture/pull/74.html" title="Last updated on Jun 11, 2018, 3:19 PM GMT (68849f9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/74/eeaaf21...foolip:68849f9.html" title="Last updated on Jun 11, 2018, 3:19 PM GMT (68849f9)">Diff</a>

Update web-platform-tests URLs

---

index.bs

FIX #79
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/84.html" title="Last updated on Sep 21, 2018, 7:42 AM GMT (28a30d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/84/586ce7e...28a30d4.html" title="Last updated on Sep 21, 2018, 7:42 AM GMT (28a30d4)">Diff</a>

Add pictureInPictureWindow to enterpictureinpicture event

---

index.bs

I've added folks that made PR or left comments/opened issues that led to PRs. Some folks didn't put their real names so I didn't add them.
@beaufortfrancois did I miss anyone?
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/85.html" title="Last updated on Sep 24, 2018, 6:34 PM GMT (b26aa8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/85/586ce7e...b26aa8f.html" title="Last updated on Sep 24, 2018, 6:34 PM GMT (b26aa8f)">Diff</a>

Add Acknowledgments section

---

index.bs

Following https://github.com/GoogleChrome/samples/pull/615, I've updated our examples section. 
What do you think @mounirlamouri?
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/86.html" title="Last updated on Sep 25, 2018, 1:29 PM GMT (c18f05b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/86/d11dde2...c18f05b.html" title="Last updated on Sep 25, 2018, 1:29 PM GMT (c18f05b)">Diff</a>

Update PiP examples

---

index.bs

This pull request takes advantage of some of the Bikeshed feature suggested in issue https://github.com/WICG/shape-detection-api/issues/49.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/89.html" title="Last updated on Oct 3, 2018, 7:53 AM GMT (bf24598)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/89/2352bbf...bf24598.html" title="Last updated on Oct 3, 2018, 7:53 AM GMT (bf24598)">Diff</a>

Bikeshed usage cleanup

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/95.html" title="Last updated on Oct 24, 2018, 7:46 AM GMT (e4fc541)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/95/d7b0f01...e4fc541.html" title="Last updated on Oct 24, 2018, 7:46 AM GMT (e4fc541)">Diff</a>

Add maximum picture-in-picture window size

---

index.bs

FYI @zouhir
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/96.html" title="Last updated on Oct 24, 2018, 7:44 AM GMT (8a357a3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/96/d7b0f01...8a357a3.html" title="Last updated on Oct 24, 2018, 7:44 AM GMT (8a357a3)">Diff</a>

Add Zouhir Chahoud to acknowledgments section

---

index.bs

FIX #80
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/82.html" title="Last updated on Oct 24, 2018, 1:50 PM GMT (44db90c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/82/6dca358...44db90c.html" title="Last updated on Oct 24, 2018, 1:50 PM GMT (44db90c)">Diff</a>

Add "Interaction with Page Visibility" section

---

index.bs

TBR @mounirlamouri
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/100.html" title="Last updated on Nov 23, 2018, 4:08 PM GMT (ba8ae18)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/100/4fb502c...ba8ae18.html" title="Last updated on Nov 23, 2018, 4:08 PM GMT (ba8ae18)">Diff</a>

Add link for reflect

---

index.bs

TBR @mounirlamouri
Thank you @yoavweiss!
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/104.html" title="Last updated on Nov 26, 2018, 1:20 PM GMT (a7873d2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/104/ed25bd1...a7873d2.html" title="Last updated on Nov 26, 2018, 1:20 PM GMT (a7873d2)">Diff</a>

Add Yoav Weiss to acknowledgments

---

index.bs

@yoavweiss had some feedback. Thanks! This PR addresses some of it.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/101.html" title="Last updated on Nov 27, 2018, 3:34 PM GMT (3782973)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/101/ed25bd1...3782973.html" title="Last updated on Nov 27, 2018, 3:34 PM GMT (3782973)">Diff</a>

Spec rewording

---

index.bs

I've just had a quick read through the PiP spec, looks great so far! I made a few editorial changes as I was reading. The main one is that some text and the examples used the term "Picture-in-Picture mode", but elsewhere this is simply "Picture-in-Picture", so I edited to use "Picture-in-Picture mode" throughout. I hope these changes are OK with you.
***
<a href="https://pr-preview.s3.amazonaws.com/chrisn/picture-in-picture/pull/118.html" title="Last updated on Feb 8, 2019, 6:08 PM UTC (81a101c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/118/b926a27...chrisn:81a101c.html" title="Last updated on Feb 8, 2019, 6:08 PM UTC (81a101c)">Diff</a>

Some editorial changes

---

index.bs

Clarify text around Auto Picture-in-Picture

---

deploy.sh

Updates the deploy.sh script on the v2 branch to build the HTML into the out/v2 directory

Edit deploy script for v2 branch

---

README.md
index.bs

Edit the abstract and links to clarify this is a proposed new iteration of the spec for arbitrary content

Edit abstract and links

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/135.html" title="Last updated on Apr 30, 2019, 11:50 PM UTC (3a1920b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/135/a418f15...3a1920b.html" title="Last updated on Apr 30, 2019, 11:50 PM UTC (3a1920b)">Diff</a>

Add arbitrary content example

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/137.html" title="Last updated on May 3, 2019, 10:45 PM UTC (78bde37)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/137/2fbbc55...78bde37.html" title="Last updated on May 3, 2019, 10:45 PM UTC (78bde37)">Diff</a>

Merge new changes from master to v2

---

v2_explainer.md

There was feedback from the TAG that it would be useful if the explainer started from the user benefit. The original explainer did a good job of this, so this copies the intro as background to the V2 explainer.

Update V2 explainer

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/133.html" title="Last updated on May 24, 2019, 5:43 PM UTC (c3b221a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/133/2fbbc55...c3b221a.html" title="Last updated on May 24, 2019, 5:43 PM UTC (c3b221a)">Diff</a>

Define arbitrary content and interactivity

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/138.html" title="Last updated on May 24, 2019, 9:08 PM UTC (0ca993a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/138/e5eaadc...0ca993a.html" title="Last updated on May 24, 2019, 9:08 PM UTC (0ca993a)">Diff</a>

Write security considerations for arbitrary content

---

implementation-status.md

FYI @mounirlamouri @marcoscaceres 
Issue https://github.com/WICG/picture-in-picture/pull/152

Update Safari implementation status page

---

implementation-status.md

@marcoscaceres Does that look good to you?
FYI @mounirlamouri 
Issue #152

Update Firefox implementation status

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/176.html" title="Last updated on Feb 4, 2020, 12:59 AM UTC (e30c229)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/176/9a28dfa...e30c229.html" title="Last updated on Feb 4, 2020, 12:59 AM UTC (e30c229)">Diff</a>

Link to /TR

---

implementation-status.md

@MarionDaly Let me know if that looks good to you.
FYI @marcoscaceres @mounirlamouri 
Issue https://github.com/WICG/picture-in-picture/pull/152

Updated implementation status

---

index.bs

FIX #175
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/pull/185.html" title="Last updated on Jun 11, 2020, 7:52 AM UTC (2a848ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/picture-in-picture/185/9a28dfa...2a848ec.html" title="Last updated on Jun 11, 2020, 7:52 AM UTC (2a848ec)">Diff</a>

Add interaction with fullscreen section

---

index.bs

FIX https://github.com/w3c/picture-in-picture/issues/188

leavepictureinpicture event fires with Picture-in-Picture window

---

index.bs

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/pull/149.html" title="Last updated on Jun 3, 2019, 8:32 AM UTC (930ff12)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/picture-in-picture/149/f8dae9f...930ff12.html" title="Last updated on Jun 3, 2019, 8:32 AM UTC (930ff12)">Diff</a>

Editorial: small suggestions for examples

---

README.md

Remove edge wpt badge
